language: node_js
node_js: "8"
branches:
  only:
  - master
cache:
  directories:
    - node_modules
before_install:
  - psql -c "CREATE USER root WITH PASSWORD 'password';" 
  - mysql -e 'CREATE DATABASE testdb;'
  # - mysql -e 'CREATE DATABASE user_profile_db;'
